FROM {{ namespace }}/{{ image_prefix }}octopus-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block octopus_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set octopus_api_packages = [
                'httpd',
                'mod_ssl',
                'openstack-octopus-api'
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set octopus_api_packages = octopus_api_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set octopus_api_packages = octopus_api_packages + ['mod_wsgi'] %}
        {% endif %}
{{ macros.install_packages(octopus_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_package_type == 'deb' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{% elif install_type == 'source' %}

    {% if base_package_type == 'rpm' %}
        {% set octopus_api_packages = [
                'httpd',
                'mod_ssl',
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set octopus_api_packages = octopus_api_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set octopus_api_packages = octopus_api_packages + ['mod_wsgi'] %}
        {% endif %}
{{ macros.install_packages(octopus_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_package_type == 'deb' %}
        {% set octopus_api_packages = [
                'apache2',
                'libapache2-mod-wsgi-py3'
        ] %}
{{ macros.install_packages(octopus_api_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf

    {% endif %}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_octopus_extend_start
RUN chmod 755 /usr/local/bin/kolla_octopus_extend_start

{% block octopus_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
